import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:arena_flow/core/theme/app_theme.dart';
import 'package:arena_flow/features/queue_tracker/presentation/pages/express_queue_page.dart';

void main() {
  Widget createWidgetUnderTest() {
    return MaterialApp(
      theme: AppTheme.darkTheme,
      home: const ExpressQueuePage(),
    );
  }

  group('ExpressQueuePage Widget Tests', () {
    testWidgets('Should display search bar and queue items', (WidgetTester tester) async {
      await tester.pumpWidget(createWidgetUnderTest());
      await tester.pumpAndSettle();

      // Verify Search bar exists
      expect(find.byType(TextField), findsOneWidget);
      expect(find.text('Search Stands (Sanitized Input)'), findsOneWidget);

      // Verify list items generated by ListView.builder
      expect(find.text('Burger Dash'), findsWidgets);
      expect(find.text('Stadium Pizza'), findsWidgets);
    });

    testWidgets('Should open Order Dialog when Express Order button is tapped', (WidgetTester tester) async {
      await tester.pumpWidget(createWidgetUnderTest());
      await tester.pumpAndSettle();

      // Find the first order button
      final orderButton = find.widgetWithText(ElevatedButton, 'Order').first;
      expect(orderButton, findsOneWidget);

      // Tap it
      await tester.tap(orderButton);
      await tester.pumpAndSettle(); // Wait for animation

      // Verify dialog is displaying
      expect(find.byType(AlertDialog), findsOneWidget);
      expect(find.textContaining('Express Order:'), findsOneWidget);
      
      // Verify actions
      expect(find.text('Confirm'), findsOneWidget);
      expect(find.text('Cancel'), findsOneWidget);
      
      // Tap Confirm
      await tester.tap(find.text('Confirm'));
      await tester.pumpAndSettle();

      // Verify dialog closed and snackbar shown
      expect(find.byType(AlertDialog), findsNothing);
      expect(find.text('Order Placed Successfully!'), findsOneWidget);
    });
  });
}
